### ISSUE TITLE
Add Bintray credentials to .travis.yml

### ISSUE THREAD

**Issue by BenFradet** [snowplow-referer-parser/java-referer-parser#4]
- BINTRAY_SNOWPLOW_MAVEN_USER
- BINTRAY_SNOWPLOW_MAVEN_API_KEY

**Comment by alexanderdean** [comment]
Really? Don't you mean the `MAVEN_USER` creds @BenFradet ?

**Comment by BenFradet** [comment]
Indeed, thanks!

**Comment by alexanderdean** [comment]
Done!
